# Generated by Django 5.1.2 on 2024-12-02 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='answer',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='question',
            new_name='text',
        ),
        migrations.AddField(
            model_name='answermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
