# Generated by Django 5.1.2 on 2024-12-03 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('quiz', '0003_resultsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='company.company'),
        ),
    ]
