# Generated by Django 5.1.2 on 2024-12-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizmodel_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsmodel',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
