name: Deploy to EC2

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dos2unix
      run: sudo apt-get update && sudo apt-get install -y dos2unix

    - name: Convert PEM file to Unix format
      run: dos2unix ./quiz-backend.pem

    - name: Upload project files to EC2
      run: |
        chmod 400 ./quiz-backend.pem
        scp -i ./quiz-backend.pem -r * ec2-user@51.20.42.23:/home/ec2-user/downloads

    - name: Rebuild and restart Docker container
      run: |
        ssh -i ./quiz-backend.pem -o StrictHostKeyChecking=no ec2-user@51.20.42.23 << EOF
        cd /home/ec2-user/app
        docker-compose down
        docker-compose up --build
        EOF
