name: Deploy to EC2

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dos2unix
      run: sudo apt-get update && sudo apt-get install -y dos2unix

    - name: Create PEM file from GitHub secret
      run: |
        echo "${{ secrets.PEM_FILE }}" > ./quiz-backend.pem
        dos2unix ./quiz-backend.pem
        chmod 400 ./quiz-backend.pem

    - name: Print absolute path
      run: |
        echo "Full path to quiz-backend.pem: $(pwd)/quiz-backend.pem"

    - name: Add EC2 host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 51.20.42.23 >> ~/.ssh/known_hosts

    - name: Upload project files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i $(pwd)/quiz-backend.pem -r * ec2-user@51.20.42.23:/home/ec2-user/downloads

    - name: Rebuild and restart Docker container
      run: |
        ssh -i ./quiz-backend.pem -o StrictHostKeyChecking=no ec2-user@51.20.42.23 << EOF
        cd /home/ec2-user/app
        docker-compose down
        docker-compose up --build
        EOF
