name: Deploy to EC2

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create PEM file from GitHub secret
      run: |
        echo "${{ secrets.AWS_PEM_KEY }}" > ./quiz-backend.pem
        chmod 400 ./quiz-backend.pem

    - name: Upload project files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ./quiz-backend.pem -r * ec2-user@51.20.42.23:/home/ec2-user/downloads

    - name: Rebuild and restart Docker container
      run: |
        ssh -i ./quiz-backend.pem -o StrictHostKeyChecking=no ec2-user@51.20.42.23 << EOF
        cd /home/ec2-user/app
        docker-compose down
        docker-compose up --build
        EOF
