name: Run Quizz Workflow
on:
  push:
    branches:
      - "**"
jobs:
  quiz:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    outputs:
      poetry-cache-path: ${{ steps.poetry-cache-path.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Cache Poetry dependencies
        id: poetry-cache-path
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        if: steps.poetry-cache-path.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Show Poetry version
        run: poetry --version

      - name: Run ruff lint
        run: poetry run ruff check

      - name: Run tests
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          DEBUG: ${{ secrets.DEBUG }}
          DATABASE_URL: postgres://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@${{secrets.POSTGRES_HOST}}:${{secrets.POSTGRES_PORT || 5432}}/${{secrets.POSTGRES_DB}}
        continue-on-error: true
        run: poetry run python -m core.manage test

      - name: Run migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          CORS_ORIGIN_ALLOW_ALL: ${{secrets.CORS_ORIGIN_ALLOW_ALL}}
          CORS_ORIGIN_WHITELIST: ${{secrets.CORS_ORIGIN_WHITELIST}}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: 5432
        run: poetry run python -m core.manage migrate