name: Django Testing
run-name: ${{github.actor}} is testing out Django 🚀
on:
  push:
    branches:
      - "**"

jobs:
  setup:
    name: Setup Enviroment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction
  lint:
    runs-on: ubuntu-latest
    name: Linting Django project
    needs: setup
    steps:
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Run linter(Ruff)
        run: |
          source .venv/bin/activate
          ruff check

  migrations:
    name: Migrations Test
    needs: [ setup,lint ]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
      POSTGRES_PORT: ${{secrets.POSGRES_PORT}}
    steps:
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: List files for debugging
        run: ls -R /home/runner/work/meduzzen_backend/

      - name: Run migrations
        run: |
          source .venv/bin/activate
          python /home/runner/work/meduzzen_backend/core/manage.py makemigrations
          python /home/runner/work/meduzzen_backend/core/manage.py migrate


  tests:
    name: Django Test
    needs: [ setup, lint, migrations ]
    runs-on: ubuntu-latest
    steps:
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Run Tests
        run: |
          source venv/bin/activate
          python /home/runner/work/meduzzen_backend/core/manage.py test